@baseUrl={{BASE_URL}}

###
PUT {{baseUrl}}/api/people/67c77816aca0141bd45373c7 HTTP/1.1
Content-Type: application/json

{
    "name": "arz",
    "number": "50001-30342"
}

###

POST {{baseUrl}}/api/people HTTP/1.1
Content-Type: application/json

{   
    "name": "arzsdsz lkelklew",
    "number": "50001-3034"
}

###
DELETE {{baseUrl}}/api/people/67c77816aca0141bd45373c7

###
GET {{baseUrl}}/api/people/64a9d1e0e483339b9bebaacf

###
GET {{baseUrl}}/api/people

### 
GET {{baseUrl}}/api/info

// http://127.0.0.1:3001/
// https://holy-cloud-6420.fly.dev/api/info