
POST https://holy-cloud-6420.fly.dev/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "martina navarda",
    "number": "500060040"
}

###
DELETE https://holy-cloud-6420.fly.dev/api/persons/2

###
GET https://holy-cloud-6420.fly.dev/api/persons/4

###
GET https://holy-cloud-6420.fly.dev/api/persons

### 
GET https://holy-cloud-6420.fly.dev/api/info