GET http://apractice.eba-kph2xfd6.eu-west-1.elasticbeanstalk.com/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "The VS Code REST client is very useful",
    "important": false
}