GET http://fso-practice22.eu-west-1.elasticbeanstalk.com:5000/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "The VS Code REST client is very useful",
    "important": false
}